name: 'API-$(majorVersion).$(minorVersion).$(patchVersion).$(rev:r)'

trigger:
- release/*
- R_*
- hotfix/*
- feature/*
- main
- S_*

pool:
  vmImage: 'windows-latest'

variables:
  majorVersion: 0
  minorVersion: 0
  patchVersion: 1
  buildConfiguration: 'Release'
  projectName: 'AzureDemoProj'
  publishArtifact: 'True'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: and(succeeded(), eq(variables['publishArtifact'], 'True'))
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $publishArtifact = $env:PUBLISHARTIFACT
      if ($env:BUILD_SOURCEBRANCHNAME -like "main" -Or $env:BUILD_SOURCEBRANCHNAME -like "R_*") {
        $publishArtifact = "True"
      } else {
        $publishArtifact = "False"
      }
      Write-Host "##vso[task.setvariable variable=publishArtifact;]$publishArtifact"


- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '*/.csproj'
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Publish Package'
  condition: and(succeeded(), eq(variables['publishArtifact'], 'True'))
  inputs:
    command: 'publish'
    projects: '*/$(projectName)/.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(50de5f22-80d8-4e7a-934b-5f557c4d3f78)'
    appType: 'webApp'
    WebAppName: 'demo-training'
    packageForLinux: '$(System.DefaultWorkingDirectory)/webApp.zip'