trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution:'**/*.sln'
  buildPlatform:'Any CPU'  
  buildConfiguration:'Release'

steps:
- task: NuGetToolInstaller@1
 

- task: NuGetCommand@2
  inputs:
	restoreSolution: '$(solution)'


- task:
  inputs:
	solution: '$(solution)'
	msbuildArgs :'/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\wepApp.zip"'
	platform: '$(buildPlatform)'
	configuration:'$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(50de5f22-80d8-4e7a-934b-5f557c4d3f78)'
    appType: 'webApp'
    WebAppName: 'demoazpro'
    packageForLinux: '$(build.artifactstagingdirectory)\wepApp.zip'